### ISSUE TITLE
1.21.1 - Can't respawn or go to menu when dead

### ISSUE THREAD

**Issue by nobewayo** [borisshoes/LimitedAFK#1]
Fabric 0.16.7
MC 1.21.1
Limited AFK version 1.4.0-1.21 (newest)
Fresh server, no other mods.

When I die and try to press Respawn or Main menu, the button just gets greyed out and won't allow me to respawn again.

![image](https://github.com/user-attachments/assets/b4f460eb-fd52-4ff5-b03c-bac8b85dbd71)

**Comment by borisshoes** [comment]
Thanks for submitting a bug report!
Does this only occur when you die while AFK, or after any death?

**Comment by nobewayo** [comment]
Any death.

**Comment by borisshoes** [comment]
The latest version now fixes this bug. Apologies for the wait.
